server:
  port: 8989
  context-path: /hotel_zyc
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hotel
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760

mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:mapper/*.xml
#分页插件相关参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

